# Generated by Django 3.0.4 on 2020-03-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200309_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='messenger',
            field=models.CharField(max_length=255, null=True, verbose_name='messenger'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=64, null=True, verbose_name='phone_number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.CharField(max_length=64, null=True, verbose_name='telegram'),
        ),
    ]
