# Generated by Django 3.0.4 on 2020-03-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200310_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='messenger',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='messenger'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='telegram'),
        ),
    ]
