# Generated by Django 3.0.4 on 2020-03-11 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('friend_name', models.CharField(max_length=255, verbose_name='friend_name')),
                ('info', models.CharField(max_length=255, verbose_name='information')),
                ('phone_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='phone_number')),
                ('telegram', models.CharField(blank=True, max_length=64, null=True, verbose_name='telegram')),
                ('messenger', models.CharField(blank=True, max_length=255, null=True, verbose_name='messenger')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
